export enum Sports {
    Futebol5 = 1,
    Futebol7,
    Tenis,
    Padel,
    Futebol11,
    Futsal,
    Basketball = 8,
    Andebol,
    Voleibol,
    Padbol = 12,
    BubbleFootball,
    Squash,
    Rugby,
    SalasDeDesporto,
    Futebol5Tabelas,
    Golf,
    TenisDePraia,
    PistasAtletismo,
    Futvolei,
    Teqball,
    Futetenis,
    Natacao,
    PingPong,
    HoqueiPatins,
    PatinagemArtistica,
}